autosmelt:
  fortune:
    IRON_INGOT:
      1:
        base: 66
        max : 2
      2:
        base: 50
        max : 3
      3:
        base: 40
        max : 4
    GOLD_INGOT:
      1:
        base: 66
        max : 2
      2:
        base: 50
        max : 3
      3:
        base: 40
        max : 4

autoblock:
  craftables:
    - COAL:COAL_BLOCK:9
    - IRON_INGOT:IRON_BLOCK:9
    - REDSTONE:REDSTONE_BLOCK:9
    - GOLD_NUGGET:GOLD_INGOT:9
    - GOLD_INGOT:GOLD_BLOCK:9
    - LAPIS_LAZULI:LAPIS_BLOCK:9
    - EMERALD:EMERALD_BLOCK:9
    - DIAMOND:DIAMOND_BLOCK:9
    - QUARTZ:QUARTZ_BLOCK:4

notifications:
  default_on: true

messages:
  prefix: true
  autopickup:
    enabled: AutoPickup enabled!
    disabled: AutoPickup disabled!
    already_enabled: AutoPickup already enabled!
    already_disabled: AutoPickup already disabled!
  autosmelt:
    enabled: AutoSmelt enabled!
    disabled: AutoSmelt disabled!
    already_enabled: AutoSmelt already enabled!
    already_disabled: AutoSmelt already disabled!
  notifications:
    enabled: Notifications enabled!
    disabled: Notifications disabled!
    already_enabled: Notifications already enabled!
    already_disabled: Notifications already disabled!
  autoblock:
    enabled: AutoBlock enabled!
    disabled: AutoBlock disabled!
    already_enabled: AutoBlock already enabled!
    already_disabled: AutoBlock already disabled!
  help:
    autopickup_help:
      - /ap <on|off> - Enables/Disables AutoPickup
      - /ap - Toggles AutoPickup
      - /as <on|off> - Enables/Disables AutoSmelt
      - /as - Toggles AutoSmelt
      - /an <on|off> - Enables/Disables Notifications
      - /an - Toggles Notifications
      - /ab <on|off> - Enables/Disables AutoBlock
      - /ab - Toggles AutoBlock
      - /ab all - AutoBlocks all suitable ingots in inventory

  unauthorized: You do not have the permission to use that command!
  full_inventory: Your inventory is full!
  reloading: Reloading...
  reloading_unsuccessful: Reloading not successful, plugin in undetermined state. Please see logging for details!
  reloading_successful: Reloading successful!

sound:
  enabled: true
api:
  placeholder:
    enabled: true
    messages:
      true: "True"
      false: "False"

