name: AutoPickupPlugin
version: 0.6
main: com.backslide999.autopickup.AutoPickupPlugin
api-version: 1.13
authors: [Backslide999]
description: Used for auto aquiring materials upon mining

commands:

  autopickup:
    description: Enables or disables AutoPickupPlugin
    aliases: [ap, apickup]
    permission: autopickup.autopickup
    permission-message: §cYou do not have permission to use that command!
    usage: §9/autopickup help

  autonotify:
    description: Enables or disables AutoPickupPlugin notifications
    aliases: [an, anotify]
    permission: autopickup.notifications
    permission-message: §cYou do not have permission to use that command!
    usage: §9/autopickup help

  autosmelt:
    description: Enables or disables AutoSmelt
    aliases: [as, asmelt]
    permission: autopickup.autosmelt
    permission-message: §cYou do not have the permission to use that command!
    usage: §9/autopickup help

permissions:

  autopickup.*:
    description: Allows autopickup commands
    default: op
    children:
      autopickup.autopickup: true
      autopickup.notification: true
      autopickup.autosmelt: true

  autopickup.autopickup:
    description: Allows autopickup enabling
    default: op

  autopickup.notification:
    description: Allows autopickup notifications
    default: op

  autopickup.autosmelt:
    description: Allows autosmelt
    default: op
    children:
    autopickup.autosmelt.fortune:
      description: Allows fortune on mining gold- and iron ores
      default: op