name: AutoAquirePlugin
version: 0.3
main: com.backslide999.autoaquire.AutoAquirePlugin
api-version: 1.13
authors: [Backslide999]
description: Used for auto aquiring materials upon mining

commands:

  autoaquire:
    description: Enables or disables AutoAquirePlugin
    aliases: [aa, aquire]
    permission: autoaquire.autoaquire
    permission-message: §cYou do not have permission to use that command!
    usage: §9/autoaquire help

  autonotify:
    description: Enables or disables AutoAquirePlugin notifications
    aliases: [an, anotify]
    permission: autoaquire.notifications
    permission-message: §cYou do not have permission to use that command!
    usage: §9/autoaquire help

  autofurnace:
    description: Enables or disables AutoFurnace
    aliases: [af, afurnace]
    permission: autoaquire.autofurnace
    permission-message: §cYou do not have the permission to use that command!
    usage: §9/autoaquire help

permissions:

  autoaquire.*:
    description: Allows autoaquire commands
    default: op
    children:
      autoaquire.autoaquire: true
      autoaquire.notification: true
      autoaquire.autofurnace: true

  autoaquire.autoaquire:
    description: Allows autoaquire enabling
    default: op

  autoaquire.notification:
    description: Allows autoaquire notifications
    default: op

  autoaquire.autofurnace:
    description: Allows autofurnca
    default: op